### PR TITLE
Updated tabler to beta10

### PR DESCRIPTION
**Pull request by wucherpfennig**
## Description
fix for #95 

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist
- [ ] I updated the documentation (see [here](https://github.com/kevinpapst/TablerBundle/tree/master/docs))
- [x] I agree that this code will be published under the [MIT license](https://github.com/kevinpapst/TablerBundle/blob/master/LICENSE)

### CODE REVIEW

**Comment by kevinpapst** [comment]
How did you do that if https://www.npmjs.com/package/@tabler/core still shows beta9?

**Comment by wucherpfennig** [comment]
I went to and selected https://www.npmjs.com/package/@tabler/core/v/1.0.0-beta10

After that I installed the specific version:

npm i @tabler/core@1.0.0-beta10

**Comment by kevinpapst** [comment]
Ups, seems I am not as experienced with npm package manager as I am with composer^^
Thanks for helping out! I will give it a test later on and merge afterwards.

**Comment by wucherpfennig** [comment]
No worries my experience is limited to composer too 😉😎

**Pull request merged**
