### PR TITLE
[button] Update `icon` class condition

### LINKED ISSUE #144: [Button] `btn-sm` and `icon` class
Displaying button with `btn-sm` WITH an icon creates an ugly button.
Due to the `icon` class on the FontAwesome <i>, it oversize the icon.

image

```html
<a href="#" class="btn btn-default  btn-icon btn-sm">
   <i class="icon fas fa-search-location"></i>
</a>
```

https://github.com/kevinpapst/TablerBundle/blob/8e27c726a2942b8f274904928bac8958b5cad2d0/templates/components/button.html.twig#L56

Removing that `icon` class resolve this display
image

```diff
<a href="#" class="btn btn-default  btn-icon btn-sm">
-   <i class="fas fa-search-location"></i>
+   <i class="icon fas fa-search-location"></i>
</a>
```

### PR DESCRIPTION
**Pull request by cavasinf**
## Description
Should be enough to fix #144

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist
- [ ] I updated the documentation (see [here](https://github.com/kevinpapst/TablerBundle/tree/master/docs))
- [x] I agree that this code will be published under the [MIT license](https://github.com/kevinpapst/TablerBundle/blob/master/LICENSE)

### CODE REVIEW

**Comment by kevinpapst** [comment]
Does it also work, when you have text next to the icon?

**Comment by kevinpapst** [comment]
Update: I checked the Demo application and many buttons look wrong:
Bildschirm­foto 2023-02-15 um 14 41 54
This damned `icon` class... just makes troubles everywhere.

It looks as if we need `("sm" not in class and "lg" not in class)` and also it needs to be added to the `tabler_icon` calls in `macro action_button` and `macro link_button`

**Comment by cavasinf** [comment]
> This damned `icon` class... just makes troubles everywhere.

I also sighed when I saw this `icon` class causing problems again. 😄 

-----------------

I've never used `action_button` and `link_button`.
Why not change them to use the `button` macro like `submit_button`?

They will becomes "shortcuts" to the button macro

**Comment by cavasinf** [comment]
With also `btn-lg`

image

**Review by kevinpapst — APPROVED** [review]

**Pull request merged**
