### PR TITLE
handle null URL in navigation/menu models

### LINKED ISSUE #110: Menu item allows `null` route name but not when rendered
When building the User menu item, we allow to add `null` route name.

https://github.com/kevinpapst/TablerBundle/blob/908548e4d6ac0ed94eb3e0ab75364c8a76111e1b/src/Model/MenuItemModel.php#L59-L65

But when MenuItem is used to render the actual item, 
PHP throw an error that `null` cannot be of type `sting`.

`KevinPapst\TablerBundle\Twig\RuntimeExtension::getRouteByAlias(): Argument #1 ($routeName) must be of type string, null given`

https://github.com/kevinpapst/TablerBundle/blob/908548e4d6ac0ed94eb3e0ab75364c8a76111e1b/src/Twig/RuntimeExtension.php#L48-L52

------

#### Possible fix
When route is `null` set `#` as href link.

### PR DESCRIPTION
**Pull request by kevinpapst**
## Description

fixes #110 

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist
- [ ] I updated the documentation (see [here](https://github.com/kevinpapst/TablerBundle/tree/master/docs))
- [x] I agree that this code will be published under the [MIT license](https://github.com/kevinpapst/TablerBundle/blob/master/LICENSE)

### CODE REVIEW

**Comment by cavasinf** [comment]
Does it works with user menu ? (top bar nav)
image

**Comment by kevinpapst** [comment]
You have weird use-cases 😁 but you are correct, it wasn't possible ... fixed with the latest commit!

**Comment by cavasinf** [comment]
> You have weird use-cases 😁 but you are correct, it wasn't possible ... fixed with the latest commit!

Just looked where MenuItemModel is used 😉

**Review by cavasinf — APPROVED** [review]
LGTM 👍

**Pull request merged**
