### PR TITLE
Add `status indicator` component

### PR DESCRIPTION
**Pull request by cavasinf**
See https://preview.tabler.io/docs/statuses.html#status-indicator
#### Usage

```twig
{% from '@Tabler/components/status_indicator.html.twig' import status_indicator %}

<div class="row align-items-center text-start">
    <div class="col p-0">
        {{ status_indicator({color : item.open ? 'green' : 'red', animated : false, extraClass :'float-end' }) }}
    </div>
    <div class="col p-0">
        {{ item.open ? 'label.opened'|trans : 'label.closed'|trans }}
    </div>
</div>
```

#### Preview
image

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist
- [ ] I updated the documentation (see [here](https://github.com/kevinpapst/TablerBundle/tree/master/docs))
- [x] I agree that this code will be published under the [MIT license](https://github.com/kevinpapst/TablerBundle/blob/master/LICENSE)

### CODE REVIEW

**Comment by kevinpapst** [comment]
That is a good question, which I cannot answer without research. 
I don't like the idea of adding them to the repo ... we would have to ignore the directory at least via .gitattributes to prevent the composer package from growing in size.
Maybe it is easiest, if we include them as visible image in the PR that adds the docs page - I hope visible images will not be deleted by some automated processes.

**Comment by cavasinf** [comment]
Looking at my other PR for timeline Doc #83 
The Github static link show MY user ID. So we know who uploaded it.

When looking at the [Symfony repo for example](https://github.com/symfony/symfony), their logo is not under `user-images.githubusercontent.com` but `camo.githubusercontent.com`. 
User is not showed in that link.

Looking at gihub doc, there is an explanation for camo subdomain : https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/about-anonymized-urls

**Comment by kevinpapst** [comment]
> The Github static link show MY user ID. So we know who uploaded it.

Do you care? 😁 

I just want to assure that the image does not vanish because some process recognizes that it is not used anywhere.
But I don't care how we do it. Having it in a comment seems legit to me.

**Review by kevinpapst — APPROVED** [review]

**Comment by cavasinf** [comment]
> Do you care?

No I don't 😉 

> Having it in a comment seems legit to me

What do you mean by that ?

**Comment by kevinpapst** [comment]
> What do you mean by that ?

Not really sure hahaha  

I meant: as you did it in this PR. Upload the image how ever you like, make it part of the PR comment (like the status indictor image above) and then use it.

Probably to much talk about images^^ what do you think about a new release?

**Comment by kevinpapst** [comment]
Yes, we can release as often as we want. For now I will mark them as "Pre-Release" as in "unstable before 1.0".

But if you plan too add more stuff this week, then I will wait a couple of days.

**Comment by cavasinf** [comment]
> But if you plan too add more stuff this week, then I will wait a couple of days.

I'm in holiday this Wednesday (for most of french people), 
so go ahead and do what you plan to do. I'll follow.

**Pull request merged**
