### PR TITLE
Create carousel.html.twig

### PR DESCRIPTION
**Pull request by wucherpfennig**
## Description
Add carousel component. see #100 

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist
- [ ] I updated the documentation (see [here](https://github.com/kevinpapst/TablerBundle/tree/master/docs))
- [x] I agree that this code will be published under the [MIT license](https://github.com/kevinpapst/TablerBundle/blob/master/LICENSE)

### CODE REVIEW

**Comment by kevinpapst** [comment]
I totally forgot about this PR, so sorry!

This is huge, could you add a short documentation page with an example (which I would then add to the demo app)?

**Comment by wucherpfennig** [comment]
I have added the required docs

**Comment by wucherpfennig** [comment]
Updated docs. It's a start. far from perfect.

**Review by kevinpapst — DISMISSED** [review]
Thank you so much @wucherpfennig 👍

**Review by kevinpapst — APPROVED** [review]
I changed a couple of tiny things: 
- incoming variables changed from underscore to camelCase naming
- formatted docs and added links

**Pull request merged**
